### PR TITLE
PLANNER-2128 Make OptaPlanner a part of the nightly pipeline

### PR DESCRIPTION
**Pull request by rsynek**
Depends on https://github.com/kiegroup/optaplanner/pull/924

### CODE REVIEW

**Comment by rsynek** [comment]
@Ginxo Would you recommend any safe way of testing this? I've tested only the underlying Jenkinsfile.deploy located in the optaplanner repo (see the https://github.com/kiegroup/optaplanner/pull/924) so far.

**Comment by Ginxo** [comment]
@rsynek if you mean unit tests I recommend to use `com.homeaway.devtools.jenkins:jenkins-spock` as we do in https://github.com/kiegroup/jenkins-pipeline-shared-libraries/tree/master/test/vars
Otherwise you will have to run it directly in the rhba jenkins instance. We still investigating proper ways for Jenkins integration testing

**Review by Ginxo — APPROVED** [review]
LGTM

**Comment by rsynek** [comment]
@cristianonicolai would you please review this one too and merge if it's ok? Thanks!

**Comment by cristianonicolai** [comment]
@rsynek does Optaplanner and Kogito cross depend somehow? Maybe that could be its own independent build?

**Comment by rsynek** [comment]
@cristianonicolai OptaPlanner depends on Kogito, specifically now it depends on Kogito snapshots to resolve any incompatibilities as soon as possible. Making OptaPlanner a part of the Kogito nightly pipeline is the first step; the next step is to integrate with the release pipeline so that we can release OptaPlanner together with Kogito every time.

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
