### PR TITLE
Remove branch pipeline: Set build info

### PR DESCRIPTION
**Pull request by radtriste**

### CODE REVIEW

**Comment by radtriste** [comment]
@mareknovotny @baldimir This one should be safe to merge. It is just a nice to have on Jenkins when running the job and identify easily which branch was removed ;)

**Comment by mareknovotny** [comment]
fyi @jstastny-cz

**Comment by jstastny-cz** [comment]
@mbiarnes for some reason by adding myself for review I removed you and can't add back ...

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Review by baldimir — APPROVED** [review]

**Pull request merged**
