### PR TITLE
build-chain version 2.1

### PR DESCRIPTION
**Pull request by Ginxo**
@radtriste is there any other flow using these definition and project dependencies files?
They all should be updated to `kiegroup/github-action-build-chain@v2.6`

### Referenced pull requests

- https://github.com/kiegroup/kogito-pipelines/pull/182
- https://github.com/kiegroup/kogito-examples/pull/723
- https://github.com/kiegroup/kogito-apps/pull/876
- https://github.com/kiegroup/kogito-runtimes/pull/1358
- https://github.com/kiegroup/optaplanner/pull/1365

### CODE REVIEW

**Comment by radtriste** [comment]
@Ginxo here are the projects but I don't think they need the `branch` flow-type for now
- kogito-runtimes
- kogito-apps
- kogito-examples

**Comment by radtriste** [comment]
cc @danielezonca

**Review by radtriste — APPROVED** [review]

**Comment by Ginxo** [comment]
@radtriste PRs created:

- https://github.com/kiegroup/kogito-runtimes/pull/1358
- https://github.com/kiegroup/kogito-apps/pull/876

kogito-examples does not use github-action-build-chain

**Comment by danielezonca** [comment]
> @radtriste PRs created:
> 
> * [kiegroup/kogito-runtimes#1358](https://github.com/kiegroup/kogito-runtimes/pull/1358)
> * [kiegroup/kogito-apps#876](https://github.com/kiegroup/kogito-apps/pull/876)
> 
> kogito-examples does not use github-action-build-chain

@Ginxo 
Yes it does
https://github.com/kiegroup/kogito-examples/tree/master/.github

(default branch is `stable` that link 1.6 code until we will do 1.7 release but `master` branch has github action with the same config)

**Comment by danielezonca** [comment]
@Ginxo 
Can you also update dependency file to apply mapping feature?
The rule is only for `optaplanner` and it is:
- `master` -> `master`
- `x.y.z` -> `(x+7).y.x` (i.e. `1.7.x` becomes `8.7.x`)

**Comment by Ginxo** [comment]
> @Ginxo
> Can you also update dependency file to apply mapping feature?
> The rule is only for `optaplanner` and it is:
> 
>     * `master` -> `master`
> 
>     * `x.y.z` -> `(x+7).y.x` (i.e. `1.7.x` becomes `8.7.x`)

@danielezonca Do you agree on treating on a different PR since this is blocking optaplanner and it could have side effects and would require new review process?
The one for kogito-examples open
https://github.com/kiegroup/kogito-examples/pull/723

**Comment by danielezonca** [comment]
> > @Ginxo
> > Can you also update dependency file to apply mapping feature?
> > The rule is only for `optaplanner` and it is:
> > ```
> > * `master` -> `master`
> > 
> > * `x.y.z` -> `(x+7).y.x` (i.e. `1.7.x` becomes `8.7.x`)
> > ```
> 
> @danielezonca Do you agree on treating on a different PR since this is blocking optaplanner and it could have side effects and would require new review process?
> The one for kogito-examples open
> [kiegroup/kogito-examples#723](https://github.com/kiegroup/kogito-examples/pull/723)

Fine for me, approved 👍

**Review by danielezonca — APPROVED** [review]

**Pull request merged**
