### PR TITLE
setting compare to non failure

### PR DESCRIPTION
**Pull request by elguardian**

### CODE REVIEW

**Comment by elguardian** [comment]
@porcelli @martinweiler tyring to unstack work without compromising pr. This allows to know exactly which modules are failing and do in parallel thoses fixes if require. Once the module are fixed we can go on and set this to failure = true

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Review by gitgabrio — CHANGES_REQUESTED** [review]
Please leave the exclusions as they are.
We already know those modules are not reproducible "by-design" - no need to waste time building them twice

**Review by gitgabrio — APPROVED** [review]
Thx @elguardian

**Pull request merged**
