### PR TITLE
[10.0.x] NO-ISSUE: remove incubator-kie-kogito-serverless-operator from pipelines

### PR DESCRIPTION
**Pull request by jstastny-cz**
Removing incubator-kie-kogito-serverless-operator pipeline references from kogito-pipelines config.

### CODE REVIEW

**Review by rodrigonull — APPROVED** [review]
LGTM.

**Review by wmedvede — APPROVED** [review]

**Review by wmedvede — COMMENTED** [review]
silly question, do this exclude

**Review by wmedvede — CHANGES_REQUESTED** [review]
Question, do this remove also exclude this repo from having  the CI checks?

**Comment by jstastny-cz** [comment]
@wmedvede on 10.0.x - yes, but that branch shouldn't have existed in serverless operator in the first place (if it's not part of the release).

**Review by wmedvede — APPROVED** [review]

**Pull request merged**
