### PR TITLE
KOGITO-5171 Update failure message link

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-5171

Redirect to Blue Ocean view instead of direct console

### CODE REVIEW

**Review by Ginxo — APPROVED** [review]
LGTM just check my proposal
```
                                ghprbBuildResultMessage {
                                        result('ERROR')
                                        message("The ${jobParams.pr.commitContext ?: 'Linux'} check has **an error**. Please check [the logs](${BUILD_URL}display/redirect).")
                                    }
                                    ghprbBuildResultMessage {
                                        result('FAILURE')
                                        message("The ${jobParams.pr.commitContext ?: 'Linux'} check has **failed**. Please check [the logs](${BUILD_URL}display/redirect).")
```

**Comment by radtriste** [comment]
`${BUILD_URL}` should be resolved when sending a message, not in the DSL...

But I could have (with `\${...}`)
```
ghprbBuildResultMessage {
                                        result('ERROR')
                                        message("The ${jobParams.pr.commitContext ?: 'Linux'} check has **an error**. Please check [the logs](\${BUILD_URL}display/redirect).")
                                    }
                                    ghprbBuildResultMessage {
                                        result('FAILURE')
                                        message("The ${jobParams.pr.commitContext ?: 'Linux'} check has **failed**. Please check [the logs](\${BUILD_URL}display/redirect).")
```

**Comment by Ginxo** [comment]
> `${BUILD_URL}` should be resolved when sending a message, not in the DSL...
> 
> But I could have (with `\${...}`)
> 
> ```
> ghprbBuildResultMessage {
>                                         result('ERROR')
>                                         message("The ${jobParams.pr.commitContext ?: 'Linux'} check has **an error**. Please check [the logs](\${BUILD_URL}display/redirect).")
>                                     }
>                                     ghprbBuildResultMessage {
>                                         result('FAILURE')
>                                         message("The ${jobParams.pr.commitContext ?: 'Linux'} check has **failed**. Please check [the logs](\${BUILD_URL}display/redirect).")
> ```

you are right @radtriste . Sorry for bothering you

**Comment by radtriste** [comment]
no problem. testing my proposition and will update if ok ;)

**Comment by radtriste** [comment]
all good with the tests

**Pull request merged**
