### PR TITLE
KOGITO-8090 GHA Maven cache exclude kie artifacts

### PR DESCRIPTION
**Pull request by radtriste**

### CODE REVIEW

**Comment by danielezonca** [comment]
Good idea, it is way safer :)

Is it possible also make sure that all snapshots are excluded from cache?

**Comment by radtriste** [comment]
> Good idea, it is way safer :)
> 
> Is it possible also make sure that all snapshots are excluded from cache?

I would say that this is even better, just ignoring SNAPSHOT folders/files

**Comment by radtriste** [comment]
@lampajr @danielezonca @Ginxo See https://github.com/kiegroup/kogito-pipelines/actions/runs/3969019483 for example

**Review by lampajr — APPROVED** [review]
LGTM

**Review by danielezonca — APPROVED** [review]

**Comment by radtriste** [comment]
@lampajr if we are good, then we can merge that one :)

**Pull request merged**
