### PR TITLE
KOGITO-2908 Extract create release branch

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-2908

### CODE REVIEW

**Review by Kevin-Mok — APPROVED** [review]

**Comment by Ginxo** [comment]
@radtriste why don't you follow the `Jenkins.whatever` pattern for the file `create-release-branches.Jenkinsfile` as it is followed for the rest of Jenkinsfile files? Shouldn't it be `Jenkinsfile.create-release-branches`

**Comment by radtriste** [comment]
@Ginxo Both patterns are present on kogito-pipelines but I guess we can move the others also to naming `Jenkinsfile.*`
will PR for that and update the current one as well

**Comment by radtriste** [comment]
@Ginxo could you please review and approved ? :)

**Review by Kaitou786 — APPROVED** [review]

**Review by Ginxo — APPROVED** [review]
LGTM

**Pull request merged**
