### PR TITLE
[BXMSPROD-1355][1.7.x] GA flow dynamic mapping

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-1355

related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/184
- https://github.com/kiegroup/kogito-apps/pull/879
- https://github.com/kiegroup/kogito-examples/pull/725
- https://github.com/kiegroup/kogito-runtimes/pull/1360

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
@Ginxo no Optaplanner 8.7.x ? :)

**Comment by Ginxo** [comment]
@radtriste it is not using build-chain https://github.com/kiegroup/optaplanner/blob/8.7.x/.github/workflows/os_java_ci.yml
do I clone the one from master?

**Comment by radtriste** [comment]
you are right. I mixed things. you can let it like that ;)

**Comment by radtriste** [comment]
@Ginxo Good for merging ?

**Pull request merged**
