### PR TITLE
upgraded nodejs version

### PR DESCRIPTION
**Pull request by mbiarnes**
JIRA:[BXMSPROD-1723](https://issues.redhat.com/browse/BXMSPROD-1723)

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1979
https://github.com/kiegroup/kogito-pipelines/pull/501

### CODE REVIEW

**Comment by mbiarnes** [comment]
@radtriste @Ginxo 
Does the nodejs version have to be upgraded in 7.76.x, and kogito 1.13.x --> 1.23.x too?

**Comment by Ginxo** [comment]
@mbiarnes correct me if I'm wrong, but Jenkinsfile.buildchain is a regular Jenkins' pipeline job so one single job to rule them all no matter the target branch for the PR right? it's build-chain tool the one in charge of acting accordingly to PR information. 
So if we have one single job for all the branches there's no need to update 7.67.x branch. Thanks for paying attention to it anyway.

**Review by Ginxo — APPROVED** [review]
LGTM

**Comment by mbiarnes** [comment]
@Ginxo I meant this i.e. (7.67.x):
https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/7.67.x/.ci/jenkins/Jenkinsfile.buildchain#L20
Here is specified the nodejs version. I thought it could be important?

**Review by mareknovotny — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
@mbiarnes if that is a security matter, please also update on those branches:
- 1.13.x
- 1.13.x-blue
- 1.23.x

**Pull request merged**
