### PR TITLE
KOGITO-5783 build-chain: Add project specific env vars

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-5783

This will help to set the build profile on apps and exmaples for Optaplanner PR checks.
See also https://github.com/kiegroup/kogito-apps/pull/1033 and https://github.com/kiegroup/kogito-examples/pull/897

### CODE REVIEW

**Review by Ginxo — APPROVED** [review]
LGTM 
according to

- https://github.com/kiegroup/github-action-build-chain/blob/671e0b56bbbbd77a9bc2208ba8278bc91caa73dc/src/lib/command/treatment/environment-variables-treatment.js#L8
- https://github.com/kiegroup/github-action-build-chain/blob/671e0b56bbbbd77a9bc2208ba8278bc91caa73dc/test/lib/command/treatment/environment-variables-treatment.test.js#L32

the non existing env variable should be replace by `''` so I'm ok with it.

**Review by rsynek — APPROVED** [review]

**Comment by radtriste** [comment]
just thinking this PR is missing some possibility to update the UPSTREAM Maven options. will add some

**Comment by radtriste** [comment]
@rsynek @Ginxo what do you think of the last change ?
I added upstream specific env vars. This will allow, for example, to build quickly Optaplanner with `-Dfull` property for optaplanner-quickstarts

**Comment by Ginxo** [comment]
> @rsynek @Ginxo what do you think of the last change ? I added upstream specific env vars. This will allow, for example, to build quickly Optaplanner with `-Dfull` property for optaplanner-quickstarts

I'm totally ok with it. Many thanks!

**Pull request merged**
